// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"

	"github.com/denisraison/rekan/api/internal/content/baml_client/baml_client/types"
)

type AgentAction struct {
	ActionType   *types.AgentActionType `json:"actionType"`
	ActionParams map[string]string      `json:"actionParams"`
}

func (c *AgentAction) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "AgentAction" {
		panic(fmt.Sprintf("expected AgentAction, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "actionType":
			c.ActionType = baml.Decode(valueHolder).Interface().(*types.AgentActionType)

		case "actionParams":
			c.ActionParams = baml.Decode(valueHolder).Interface().(map[string]string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class AgentAction", key))

		}
	}

}

func (c AgentAction) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["actionType"] = c.ActionType

	fields["actionParams"] = c.ActionParams

	return baml.EncodeClass("AgentAction", fields, nil)
}

func (c AgentAction) BamlTypeName() string {
	return "AgentAction"
}

type AgentResponse struct {
	Reply  *string      `json:"reply"`
	Action *AgentAction `json:"action"`
}

func (c *AgentResponse) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "AgentResponse" {
		panic(fmt.Sprintf("expected AgentResponse, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "reply":
			c.Reply = baml.Decode(valueHolder).Interface().(*string)

		case "action":
			c.Action = baml.Decode(valueHolder).Interface().(*AgentAction)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class AgentResponse", key))

		}
	}

}

func (c AgentResponse) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["reply"] = c.Reply

	fields["action"] = c.Action

	return baml.EncodeClass("AgentResponse", fields, nil)
}

func (c AgentResponse) BamlTypeName() string {
	return "AgentResponse"
}

type BusinessProfile struct {
	BusinessName   *string   `json:"businessName"`
	BusinessType   *string   `json:"businessType"`
	City           *string   `json:"city"`
	Neighbourhood  *string   `json:"neighbourhood"`
	Services       []Service `json:"services"`
	TargetAudience *string   `json:"targetAudience"`
	BrandVibe      *string   `json:"brandVibe"`
	Quirks         []string  `json:"quirks"`
}

func (c *BusinessProfile) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "BusinessProfile" {
		panic(fmt.Sprintf("expected BusinessProfile, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "businessName":
			c.BusinessName = baml.Decode(valueHolder).Interface().(*string)

		case "businessType":
			c.BusinessType = baml.Decode(valueHolder).Interface().(*string)

		case "city":
			c.City = baml.Decode(valueHolder).Interface().(*string)

		case "neighbourhood":
			c.Neighbourhood = baml.Decode(valueHolder).Interface().(*string)

		case "services":
			c.Services = baml.Decode(valueHolder).Interface().([]Service)

		case "targetAudience":
			c.TargetAudience = baml.Decode(valueHolder).Interface().(*string)

		case "brandVibe":
			c.BrandVibe = baml.Decode(valueHolder).Interface().(*string)

		case "quirks":
			c.Quirks = baml.Decode(valueHolder).Interface().([]string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class BusinessProfile", key))

		}
	}

}

func (c BusinessProfile) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["businessName"] = c.BusinessName

	fields["businessType"] = c.BusinessType

	fields["city"] = c.City

	fields["neighbourhood"] = c.Neighbourhood

	fields["services"] = c.Services

	fields["targetAudience"] = c.TargetAudience

	fields["brandVibe"] = c.BrandVibe

	fields["quirks"] = c.Quirks

	return baml.EncodeClass("BusinessProfile", fields, nil)
}

func (c BusinessProfile) BamlTypeName() string {
	return "BusinessProfile"
}

type ContentRole struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

func (c *ContentRole) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ContentRole" {
		panic(fmt.Sprintf("expected ContentRole, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(*string)

		case "description":
			c.Description = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ContentRole", key))

		}
	}

}

func (c ContentRole) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["description"] = c.Description

	return baml.EncodeClass("ContentRole", fields, nil)
}

func (c ContentRole) BamlTypeName() string {
	return "ContentRole"
}

type JudgeResult struct {
	Reasoning *string `json:"reasoning"`
	Verdict   *bool   `json:"verdict"`
}

func (c *JudgeResult) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "JudgeResult" {
		panic(fmt.Sprintf("expected JudgeResult, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "reasoning":
			c.Reasoning = baml.Decode(valueHolder).Interface().(*string)

		case "verdict":
			c.Verdict = baml.Decode(valueHolder).Interface().(*bool)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class JudgeResult", key))

		}
	}

}

func (c JudgeResult) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["reasoning"] = c.Reasoning

	fields["verdict"] = c.Verdict

	return baml.EncodeClass("JudgeResult", fields, nil)
}

func (c JudgeResult) BamlTypeName() string {
	return "JudgeResult"
}

type JudgeVariedadeResult struct {
	PostMessages []string `json:"postMessages"`
	Reasoning    *string  `json:"reasoning"`
	Verdict      *bool    `json:"verdict"`
}

func (c *JudgeVariedadeResult) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "JudgeVariedadeResult" {
		panic(fmt.Sprintf("expected JudgeVariedadeResult, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "postMessages":
			c.PostMessages = baml.Decode(valueHolder).Interface().([]string)

		case "reasoning":
			c.Reasoning = baml.Decode(valueHolder).Interface().(*string)

		case "verdict":
			c.Verdict = baml.Decode(valueHolder).Interface().(*bool)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class JudgeVariedadeResult", key))

		}
	}

}

func (c JudgeVariedadeResult) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["postMessages"] = c.PostMessages

	fields["reasoning"] = c.Reasoning

	fields["verdict"] = c.Verdict

	return baml.EncodeClass("JudgeVariedadeResult", fields, nil)
}

func (c JudgeVariedadeResult) BamlTypeName() string {
	return "JudgeVariedadeResult"
}

type PartialBusinessProfile struct {
	Services       *[]PartialService `json:"services"`
	TargetAudience *string           `json:"targetAudience"`
	BrandVibe      *string           `json:"brandVibe"`
	Quirks         *[]string         `json:"quirks"`
}

func (c *PartialBusinessProfile) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "PartialBusinessProfile" {
		panic(fmt.Sprintf("expected PartialBusinessProfile, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "services":
			c.Services = baml.Decode(valueHolder).Interface().(*[]PartialService)

		case "targetAudience":
			c.TargetAudience = baml.Decode(valueHolder).Interface().(*string)

		case "brandVibe":
			c.BrandVibe = baml.Decode(valueHolder).Interface().(*string)

		case "quirks":
			c.Quirks = baml.Decode(valueHolder).Interface().(*[]string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class PartialBusinessProfile", key))

		}
	}

}

func (c PartialBusinessProfile) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["services"] = c.Services

	fields["targetAudience"] = c.TargetAudience

	fields["brandVibe"] = c.BrandVibe

	fields["quirks"] = c.Quirks

	return baml.EncodeClass("PartialBusinessProfile", fields, nil)
}

func (c PartialBusinessProfile) BamlTypeName() string {
	return "PartialBusinessProfile"
}

type PartialService struct {
	Name     *string  `json:"name"`
	PriceBRL *float64 `json:"priceBRL"`
}

func (c *PartialService) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "PartialService" {
		panic(fmt.Sprintf("expected PartialService, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(*string)

		case "priceBRL":
			c.PriceBRL = baml.Decode(valueHolder).Interface().(*float64)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class PartialService", key))

		}
	}

}

func (c PartialService) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["priceBRL"] = c.PriceBRL

	return baml.EncodeClass("PartialService", fields, nil)
}

func (c PartialService) BamlTypeName() string {
	return "PartialService"
}

type Post struct {
	Caption        *string  `json:"caption"`
	Hashtags       []string `json:"hashtags"`
	ProductionNote *string  `json:"productionNote"`
}

func (c *Post) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Post" {
		panic(fmt.Sprintf("expected Post, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "caption":
			c.Caption = baml.Decode(valueHolder).Interface().(*string)

		case "hashtags":
			c.Hashtags = baml.Decode(valueHolder).Interface().([]string)

		case "productionNote":
			c.ProductionNote = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Post", key))

		}
	}

}

func (c Post) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["caption"] = c.Caption

	fields["hashtags"] = c.Hashtags

	fields["productionNote"] = c.ProductionNote

	return baml.EncodeClass("Post", fields, nil)
}

func (c Post) BamlTypeName() string {
	return "Post"
}

type ProfileSignal struct {
	Field *string `json:"field"`
	Value *string `json:"value"`
}

func (c *ProfileSignal) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ProfileSignal" {
		panic(fmt.Sprintf("expected ProfileSignal, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "field":
			c.Field = baml.Decode(valueHolder).Interface().(*string)

		case "value":
			c.Value = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ProfileSignal", key))

		}
	}

}

func (c ProfileSignal) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["field"] = c.Field

	fields["value"] = c.Value

	return baml.EncodeClass("ProfileSignal", fields, nil)
}

func (c ProfileSignal) BamlTypeName() string {
	return "ProfileSignal"
}

type Service struct {
	Name     *string  `json:"name"`
	PriceBRL *float64 `json:"priceBRL"`
}

func (c *Service) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Service" {
		panic(fmt.Sprintf("expected Service, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(*string)

		case "priceBRL":
			c.PriceBRL = baml.Decode(valueHolder).Interface().(*float64)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Service", key))

		}
	}

}

func (c Service) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["priceBRL"] = c.PriceBRL

	return baml.EncodeClass("Service", fields, nil)
}

func (c Service) BamlTypeName() string {
	return "Service"
}
