package agent

// Param types for agent actions.
// These were previously generated by BAML; now owned by the agent package.

type CustomerCreateParams struct {
	Name           string  `json:"name"`
	Type           string  `json:"type"`
	City           string  `json:"city"`
	Phone          *string `json:"phone,omitempty"`
	TargetAudience *string `json:"target_audience,omitempty"`
	BrandVibe      *string `json:"brand_vibe,omitempty"`
	Quirks         *string `json:"quirks,omitempty"`
}

type CustomerUpdateParams struct {
	Name           string  `json:"name"`
	Type           *string `json:"type,omitempty"`
	City           *string `json:"city,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	TargetAudience *string `json:"target_audience,omitempty"`
	BrandVibe      *string `json:"brand_vibe,omitempty"`
	Quirks         *string `json:"quirks,omitempty"`
}

type CustomerPauseParams struct {
	Name   string  `json:"name"`
	Reason *string `json:"reason,omitempty"`
}

type PostGenerateParams struct {
	Name string `json:"name"`
}

type PostApproveParams struct {
	PostId string `json:"post_id"`
	Name   string `json:"name"`
}

type PostRejectParams struct {
	PostId   string `json:"post_id"`
	Name     string `json:"name"`
	Feedback string `json:"feedback"`
}
