// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type AgentActionClassView struct {
	inner baml.ClassBuilder
}

func (t *AgentActionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AgentActionClassView) PropertyActionType() (ClassPropertyView, error) {
	return t.inner.Property("actionType")
}

func (t *AgentActionClassView) PropertyActionStatus() (ClassPropertyView, error) {
	return t.inner.Property("actionStatus")
}

func (t *AgentActionClassView) PropertyActionParams() (ClassPropertyView, error) {
	return t.inner.Property("actionParams")
}

func (t *TypeBuilder) AgentAction() (*AgentActionClassView, error) {
	bld, err := t.inner.Class("AgentAction")
	if err != nil {
		return nil, err
	}
	return &AgentActionClassView{inner: bld}, nil
}

func (t *AgentActionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type AgentResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *AgentResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AgentResponseClassView) PropertyReply() (ClassPropertyView, error) {
	return t.inner.Property("reply")
}

func (t *AgentResponseClassView) PropertyAction() (ClassPropertyView, error) {
	return t.inner.Property("action")
}

func (t *TypeBuilder) AgentResponse() (*AgentResponseClassView, error) {
	bld, err := t.inner.Class("AgentResponse")
	if err != nil {
		return nil, err
	}
	return &AgentResponseClassView{inner: bld}, nil
}

func (t *AgentResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type BusinessProfileClassView struct {
	inner baml.ClassBuilder
}

func (t *BusinessProfileClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *BusinessProfileClassView) PropertyBusinessName() (ClassPropertyView, error) {
	return t.inner.Property("businessName")
}

func (t *BusinessProfileClassView) PropertyBusinessType() (ClassPropertyView, error) {
	return t.inner.Property("businessType")
}

func (t *BusinessProfileClassView) PropertyCity() (ClassPropertyView, error) {
	return t.inner.Property("city")
}

func (t *BusinessProfileClassView) PropertyNeighbourhood() (ClassPropertyView, error) {
	return t.inner.Property("neighbourhood")
}

func (t *BusinessProfileClassView) PropertyServices() (ClassPropertyView, error) {
	return t.inner.Property("services")
}

func (t *BusinessProfileClassView) PropertyTargetAudience() (ClassPropertyView, error) {
	return t.inner.Property("targetAudience")
}

func (t *BusinessProfileClassView) PropertyBrandVibe() (ClassPropertyView, error) {
	return t.inner.Property("brandVibe")
}

func (t *BusinessProfileClassView) PropertyQuirks() (ClassPropertyView, error) {
	return t.inner.Property("quirks")
}

func (t *TypeBuilder) BusinessProfile() (*BusinessProfileClassView, error) {
	bld, err := t.inner.Class("BusinessProfile")
	if err != nil {
		return nil, err
	}
	return &BusinessProfileClassView{inner: bld}, nil
}

func (t *BusinessProfileClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ContentRoleClassView struct {
	inner baml.ClassBuilder
}

func (t *ContentRoleClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ContentRoleClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *ContentRoleClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *TypeBuilder) ContentRole() (*ContentRoleClassView, error) {
	bld, err := t.inner.Class("ContentRole")
	if err != nil {
		return nil, err
	}
	return &ContentRoleClassView{inner: bld}, nil
}

func (t *ContentRoleClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type JudgeResultClassView struct {
	inner baml.ClassBuilder
}

func (t *JudgeResultClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *JudgeResultClassView) PropertyReasoning() (ClassPropertyView, error) {
	return t.inner.Property("reasoning")
}

func (t *JudgeResultClassView) PropertyVerdict() (ClassPropertyView, error) {
	return t.inner.Property("verdict")
}

func (t *TypeBuilder) JudgeResult() (*JudgeResultClassView, error) {
	bld, err := t.inner.Class("JudgeResult")
	if err != nil {
		return nil, err
	}
	return &JudgeResultClassView{inner: bld}, nil
}

func (t *JudgeResultClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type JudgeVariedadeResultClassView struct {
	inner baml.ClassBuilder
}

func (t *JudgeVariedadeResultClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *JudgeVariedadeResultClassView) PropertyPostMessages() (ClassPropertyView, error) {
	return t.inner.Property("postMessages")
}

func (t *JudgeVariedadeResultClassView) PropertyReasoning() (ClassPropertyView, error) {
	return t.inner.Property("reasoning")
}

func (t *JudgeVariedadeResultClassView) PropertyVerdict() (ClassPropertyView, error) {
	return t.inner.Property("verdict")
}

func (t *TypeBuilder) JudgeVariedadeResult() (*JudgeVariedadeResultClassView, error) {
	bld, err := t.inner.Class("JudgeVariedadeResult")
	if err != nil {
		return nil, err
	}
	return &JudgeVariedadeResultClassView{inner: bld}, nil
}

func (t *JudgeVariedadeResultClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PartialBusinessProfileClassView struct {
	inner baml.ClassBuilder
}

func (t *PartialBusinessProfileClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PartialBusinessProfileClassView) PropertyServices() (ClassPropertyView, error) {
	return t.inner.Property("services")
}

func (t *PartialBusinessProfileClassView) PropertyTargetAudience() (ClassPropertyView, error) {
	return t.inner.Property("targetAudience")
}

func (t *PartialBusinessProfileClassView) PropertyBrandVibe() (ClassPropertyView, error) {
	return t.inner.Property("brandVibe")
}

func (t *PartialBusinessProfileClassView) PropertyQuirks() (ClassPropertyView, error) {
	return t.inner.Property("quirks")
}

func (t *TypeBuilder) PartialBusinessProfile() (*PartialBusinessProfileClassView, error) {
	bld, err := t.inner.Class("PartialBusinessProfile")
	if err != nil {
		return nil, err
	}
	return &PartialBusinessProfileClassView{inner: bld}, nil
}

func (t *PartialBusinessProfileClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PartialServiceClassView struct {
	inner baml.ClassBuilder
}

func (t *PartialServiceClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PartialServiceClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *PartialServiceClassView) PropertyPriceBRL() (ClassPropertyView, error) {
	return t.inner.Property("priceBRL")
}

func (t *TypeBuilder) PartialService() (*PartialServiceClassView, error) {
	bld, err := t.inner.Class("PartialService")
	if err != nil {
		return nil, err
	}
	return &PartialServiceClassView{inner: bld}, nil
}

func (t *PartialServiceClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PostClassView struct {
	inner baml.ClassBuilder
}

func (t *PostClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PostClassView) PropertyCaption() (ClassPropertyView, error) {
	return t.inner.Property("caption")
}

func (t *PostClassView) PropertyHashtags() (ClassPropertyView, error) {
	return t.inner.Property("hashtags")
}

func (t *PostClassView) PropertyProductionNote() (ClassPropertyView, error) {
	return t.inner.Property("productionNote")
}

func (t *TypeBuilder) Post() (*PostClassView, error) {
	bld, err := t.inner.Class("Post")
	if err != nil {
		return nil, err
	}
	return &PostClassView{inner: bld}, nil
}

func (t *PostClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ProfileSignalClassView struct {
	inner baml.ClassBuilder
}

func (t *ProfileSignalClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ProfileSignalClassView) PropertyField() (ClassPropertyView, error) {
	return t.inner.Property("field")
}

func (t *ProfileSignalClassView) PropertyValue() (ClassPropertyView, error) {
	return t.inner.Property("value")
}

func (t *TypeBuilder) ProfileSignal() (*ProfileSignalClassView, error) {
	bld, err := t.inner.Class("ProfileSignal")
	if err != nil {
		return nil, err
	}
	return &ProfileSignalClassView{inner: bld}, nil
}

func (t *ProfileSignalClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ServiceClassView struct {
	inner baml.ClassBuilder
}

func (t *ServiceClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ServiceClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *ServiceClassView) PropertyPriceBRL() (ClassPropertyView, error) {
	return t.inner.Property("priceBRL")
}

func (t *TypeBuilder) Service() (*ServiceClassView, error) {
	bld, err := t.inner.Class("Service")
	if err != nil {
		return nil, err
	}
	return &ServiceClassView{inner: bld}, nil
}

func (t *ServiceClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
