// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type AgentActionStatusEnumView struct {
	inner baml.EnumBuilder
}

func (t *AgentActionStatusEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AgentActionStatusEnumView) ValueEXECUTE() (EnumValueView, error) {
	return t.inner.Value("EXECUTE")
}

func (t *AgentActionStatusEnumView) ValueNEEDS_CONFIRMATION() (EnumValueView, error) {
	return t.inner.Value("NEEDS_CONFIRMATION")
}

func (t *TypeBuilder) AgentActionStatus() (*AgentActionStatusEnumView, error) {
	bld, err := t.inner.Enum("AgentActionStatus")
	if err != nil {
		return nil, err
	}
	return &AgentActionStatusEnumView{inner: bld}, nil
}

func (t *AgentActionStatusEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type AgentActionTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *AgentActionTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AgentActionTypeEnumView) ValueSTATUS_OVERVIEW() (EnumValueView, error) {
	return t.inner.Value("STATUS_OVERVIEW")
}

func (t *AgentActionTypeEnumView) ValueCUSTOMER_LIST() (EnumValueView, error) {
	return t.inner.Value("CUSTOMER_LIST")
}

func (t *AgentActionTypeEnumView) ValueCUSTOMER_CREATE() (EnumValueView, error) {
	return t.inner.Value("CUSTOMER_CREATE")
}

func (t *AgentActionTypeEnumView) ValueCUSTOMER_UPDATE() (EnumValueView, error) {
	return t.inner.Value("CUSTOMER_UPDATE")
}

func (t *AgentActionTypeEnumView) ValueCUSTOMER_PAUSE() (EnumValueView, error) {
	return t.inner.Value("CUSTOMER_PAUSE")
}

func (t *AgentActionTypeEnumView) ValueCUSTOMER_INFO() (EnumValueView, error) {
	return t.inner.Value("CUSTOMER_INFO")
}

func (t *AgentActionTypeEnumView) ValuePOST_GENERATE() (EnumValueView, error) {
	return t.inner.Value("POST_GENERATE")
}

func (t *AgentActionTypeEnumView) ValuePOST_LIST_PENDING() (EnumValueView, error) {
	return t.inner.Value("POST_LIST_PENDING")
}

func (t *AgentActionTypeEnumView) ValuePOST_APPROVE() (EnumValueView, error) {
	return t.inner.Value("POST_APPROVE")
}

func (t *AgentActionTypeEnumView) ValuePOST_REJECT() (EnumValueView, error) {
	return t.inner.Value("POST_REJECT")
}

func (t *TypeBuilder) AgentActionType() (*AgentActionTypeEnumView, error) {
	bld, err := t.inner.Enum("AgentActionType")
	if err != nil {
		return nil, err
	}
	return &AgentActionTypeEnumView{inner: bld}, nil
}

func (t *AgentActionTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}
