// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/denisraison/rekan/api/internal/content/baml_client/baml_client/stream_types"
	"github.com/denisraison/rekan/api/internal/content/baml_client/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.AgentAction":                   reflect.TypeOf(types.AgentAction{}),
	"STREAM_TYPES.AgentAction":            reflect.TypeOf(stream_types.AgentAction{}),
	"TYPES.AgentResponse":                 reflect.TypeOf(types.AgentResponse{}),
	"STREAM_TYPES.AgentResponse":          reflect.TypeOf(stream_types.AgentResponse{}),
	"TYPES.BusinessProfile":               reflect.TypeOf(types.BusinessProfile{}),
	"STREAM_TYPES.BusinessProfile":        reflect.TypeOf(stream_types.BusinessProfile{}),
	"TYPES.ContentRole":                   reflect.TypeOf(types.ContentRole{}),
	"STREAM_TYPES.ContentRole":            reflect.TypeOf(stream_types.ContentRole{}),
	"TYPES.JudgeResult":                   reflect.TypeOf(types.JudgeResult{}),
	"STREAM_TYPES.JudgeResult":            reflect.TypeOf(stream_types.JudgeResult{}),
	"TYPES.JudgeVariedadeResult":          reflect.TypeOf(types.JudgeVariedadeResult{}),
	"STREAM_TYPES.JudgeVariedadeResult":   reflect.TypeOf(stream_types.JudgeVariedadeResult{}),
	"TYPES.PartialBusinessProfile":        reflect.TypeOf(types.PartialBusinessProfile{}),
	"STREAM_TYPES.PartialBusinessProfile": reflect.TypeOf(stream_types.PartialBusinessProfile{}),
	"TYPES.PartialService":                reflect.TypeOf(types.PartialService{}),
	"STREAM_TYPES.PartialService":         reflect.TypeOf(stream_types.PartialService{}),
	"TYPES.Post":                          reflect.TypeOf(types.Post{}),
	"STREAM_TYPES.Post":                   reflect.TypeOf(stream_types.Post{}),
	"TYPES.ProfileSignal":                 reflect.TypeOf(types.ProfileSignal{}),
	"STREAM_TYPES.ProfileSignal":          reflect.TypeOf(stream_types.ProfileSignal{}),
	"TYPES.Service":                       reflect.TypeOf(types.Service{}),
	"STREAM_TYPES.Service":                reflect.TypeOf(stream_types.Service{}),

	"TYPES.AgentActionType": reflect.TypeOf(types.AgentActionType("")),
}
