version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - revive

  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: indent-error-flow
        - name: errorf
        - name: superfluous-else
        - name: unreachable-code
        - name: unused-parameter

